logo: # add logo name
title: Francis Sch. E
description: > # this means to ignore newlines until "baseurl:"
  IT Mystery Novel
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "francissch.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: Francis Sch. E
about-author: # about author
email: francissch.lee@gmail.com # your email
phone: # your pnone number
website: https://francissch.github.io # you website

# Social link
google_url:    # add url link
twitter_url:   https://twitter.com/FrancisSchLee
instagram_url: https://www.instagram.com/francisschlee/
pinterest_url: https://www.pinterest.co.kr/FrancisSchLee/
facebook_url:  https://www.facebook.com/FrancisSchLee
dribbble_url:  # add url link

# Disqus # add your discus identifier
discus_identifier: francissche 

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics: UA-9239803-18

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
